### ISSUE TITLE
패스트캠퍼스 vue.js 관련 질문 문의드립니다.

### ISSUE THREAD

**Issue by Haanpy** [ParkYoungWoong/vue3-webpack-template#2]
@ParkYoungWoong 
안녕하세요! 현재 박영웅 강사님의 프론트엔드 수업을 듣고 있습니다!
다름이 아니라 영상을 보고 따라서 코딩을 진행하는데 vue.js 파트에서 개발서버 오류가 계속납니다.

**npm run dev** 를 입력하면 **export 'createElementBlock' (imported as '_createElementBlock') was not found in 'vue'** 라는 오류가 발생하면서 개발 서버가 열리지 않아 진행을 하지 못하고 있습니다..

eslint를 학습할때까지만해도 잘 되었는데 선언적 렌더링과 입력 핸들링 파트부터 같은 오류가 반복적으로 실행되는데 혹시 도움을 받을 수 있을까요??

**Comment by ParkYoungWoong** [comment]
@Haanpy 님 안녕하세요~
남겨주신 에러 메시지로 의심 가는 부분이 있긴 합니다만,
전체적으로 코드 확인이 필요합니다.
현재 문제가 발생하는 프로젝트를 GitHub 저장소로 업로드하신 후에 링크를 보내주시면 좀 더 명확하게 도움을 드릴 수 있습니다.
가능하다면, 이후 소통은 제 메일로 부탁드리겠습니다.
thesecon@gmail.com

**Comment by ParkYoungWoong** [comment]
```js
// webpack.config.js
// 현재 프로젝트에서 모듈 경로를 찾을 수 있도록 지정.
// 특히 Windows에서 발생하는 오류 해결을 위한 코드.
// 이 코드가 없어도 잘 동작하는 경우 필요치 않음.
const _require = id => require(require.resolve(id, { paths: [require.main.path] }))

// path: NodeJS에서 파일 및 디렉토리 경로 작업을 위한 전역 모듈
const path = _require('path')
const HtmlPlugin = _require('html-webpack-plugin')
const CopyPlugin = _require('copy-webpack-plugin')
const { VueLoaderPlugin } = _require('vue-loader')
```
